package Week4;
/*Isaac Levine
 * 9/12
 * CSE007 Fall 2022: HW 2
 * The purpose of this program is to ask the user to either roll two dice, or state the number of two dice, then output the name of the roll generated by the roll of the dice, or the name of the two dice inputted by the user.
 */ 
import java.util.Scanner;

public class Craps {
    public static void main(String[] args) {

        // Initializes variables to be used in the program
        String choice = "";
        int dice1 = 0;
        int dice2 = 0;
        String dicePair = "";

        Scanner scan = new Scanner(System.in);

        do {
            System.out.println("Would you like to roll the dice or would you like to state the two dice you want to evaluate? Enter 'roll' if you want to roll the dice and 'state' if you want to state the dice. (without '', case sensitive)");
            choice = scan.next();
        } while (!choice.equals("roll") && !choice.equals("state"));
    
        switch(choice) {
            case("roll"):
                // Generates two integers between 1 and 6 inclusive to be assigned to dice1 and dice2
                dice1 = (int) ((Math.random() * 6) + 1);
                dice2 = (int) ((Math.random() * 6) + 1);
                break;
            case("state"):
                System.out.println("Enter the number of the first dice"); // Prompts the user to enter the number of the first dice
                dice1 = scan.nextInt();
                while (dice1 < 1 || dice1 > 6) { // Checks if the number inputted is in between 1 and 6 inclusive
                    System.out.println("Please enter a number in the accepted range (1-6)"); // If not in the range, user is prompted again to enter a number in the range
                    dice1 = scan.nextInt(); // New value is assigned to dice1
                System.out.println("Enter the number of the second dice"); // Repeat for dice2
                dice2 = scan.nextInt();
                } while (dice2 < 1 || dice2 > 6) { 
                    System.out.println("Please enter a number in the accepted range (1-6)");
                    dice2 = scan.nextInt();
                }
                break;
        }
        // Assigns dicePair to the String name according the to values of dice1 and dice2.
        if (dice1 == 1 && dice2 == 1) {
            dicePair = "Snake Eyes";
        } else if (dice1 == 1 && dice2 == 2 || dice1 == 2 && dice2 == 1) {
            dicePair = "Ace Deuce";
        } else if (dice1 == 1 && dice2 == 3 || dice1 == 3 && dice2 == 1) {
            dicePair = "Easy Four";
        } else if (dice1 == 1 && dice2 == 4 || dice1 == 4 && dice2 == 1) {
            dicePair = "Fever Five";
        } else if (dice1 == 1 && dice2 == 5 || dice1 == 5 && dice2 == 1) {
            dicePair = "Easy Six";
        } else if (dice1 == 1 && dice2 == 6 || dice1 == 5 && dice2 == 6) {
            dicePair = "Seven Out";   
        } else if (dice1 == 2 && dice2 == 2) {
            dicePair = "Hard Four"; 
        } else if (dice1 == 2 && dice2 == 3 || dice1 == 3 && dice2 == 2) {
            dicePair = "Fever Five";
        } else if (dice1 == 2 && dice2 == 4 || dice1 == 4 && dice2 == 2) {
            dicePair = "Easy Six";
        } else if (dice1 == 2 && dice2 == 5 || dice1 == 5 && dice2 == 2) {
            dicePair = "Seven Out";
        } else if (dice1 == 2 && dice2 == 6 || dice1 == 6 && dice2 == 2) {
            dicePair = "Easy Eight";
        } else if (dice1 == 3 && dice2 == 3) {
            dicePair = "Hard Six";
        } else if (dice1 == 3 && dice2 == 4 || dice1 == 4 && dice2 == 3) {
            dicePair = "Seven Out";
        } else if (dice1 == 3 && dice2 == 5 || dice1 == 5 && dice2 == 3) {
            dicePair = "Easy Eight";
        } else if (dice1 == 3 && dice2 == 6 || dice1 == 6 && dice2 == 3) {
            dicePair = "Nine"; 
        } else if (dice1 == 4 && dice2 == 4) {
            dicePair = "Hard Eight";
        } else if (dice1 == 4 && dice2 == 5 || dice1 == 5 && dice2 == 4) {
            dicePair = "Nine";
        } else if (dice1 == 4 && dice2 == 6 || dice1 == 6 && dice2 == 4) {
            dicePair = "Easy Ten"; 
        } else if (dice1 == 5 && dice2 == 5) {
            dicePair = "Hard Ten";
        } else if (dice1 == 5 && dice2 == 6 || dice1 == 6 && dice2 == 5) {
            dicePair = "Yo-leven";
        } else if (dice1 == 6 && dice2 == 6) {
            dicePair = "Boxcards";
        }
        //Prints the results
        System.out.println("You rolled a " + dice1 + " and a " + dice2 + ". The name of this roll is " + dicePair);
        
        scan.close(); // Closes the scanner
    }
}
